-- =============================================================
-- SIGNATURE PAYROLL SUITE - SUPABASE DATABASE SCHEMA
-- =============================================================

-- 1. EMPLOYEES TABLE
CREATE TABLE IF NOT EXISTS public.employees (
    ep_code TEXT PRIMARY KEY,
    nickname TEXT NOT NULL,
    status TEXT DEFAULT 'Active',
    base_salary NUMERIC DEFAULT 0,
    pay_group TEXT DEFAULT 'Date : 10',
    stay_outside TEXT DEFAULT 'No',
    start_date DATE,
    resign_date DATE,
    note TEXT
);

-- 2. ATTENDANCE LOG TABLE
CREATE TABLE IF NOT EXISTS public.attendance_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    log_id TEXT,
    date DATE NOT NULL,
    ep_code TEXT NOT NULL REFERENCES public.employees(ep_code) ON DELETE CASCADE,
    nickname TEXT,
    category TEXT NOT NULL DEFAULT 'Day-off',
    shift TEXT DEFAULT 'Normal',
    units NUMERIC DEFAULT 1.0,
    note TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 3. PAYROLL ADJUSTMENTS TABLE
CREATE TABLE IF NOT EXISTS public.payroll_adjustments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    adj_id TEXT,
    period TEXT NOT NULL,
    due_date DATE,
    ep_code TEXT NOT NULL REFERENCES public.employees(ep_code) ON DELETE CASCADE,
    nickname TEXT,
    type TEXT NOT NULL DEFAULT 'Deduction',
    category TEXT NOT NULL DEFAULT 'Advance',
    description TEXT,
    amount NUMERIC NOT NULL DEFAULT 0,
    status TEXT DEFAULT 'Pending',
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 4. PAYROLL SUMMARY TABLE
CREATE TABLE IF NOT EXISTS public.payroll_summary (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payroll_id TEXT,
    period TEXT NOT NULL,
    ep_code TEXT NOT NULL REFERENCES public.employees(ep_code) ON DELETE CASCADE,
    nickname TEXT,
    pay_type TEXT DEFAULT 'Full Month',
    base_salary NUMERIC DEFAULT 0,
    work_days INT DEFAULT 26,
    day_off INT DEFAULT 4,
    sick INT DEFAULT 0,
    half_day INT DEFAULT 0,
    ot_days INT DEFAULT 0,
    base_pay NUMERIC DEFAULT 0,
    total_extra NUMERIC DEFAULT 0,
    total_deduction NUMERIC DEFAULT 0,
    net_pay NUMERIC DEFAULT 0,
    status TEXT DEFAULT 'Approved',
    note TEXT,
    created_at TIMESTAMPTZ DEFAULT now(),
    UNIQUE (period, ep_code)
);

-- Enable RLS
ALTER TABLE public.employees ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.attendance_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payroll_adjustments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payroll_summary ENABLE ROW LEVEL SECURITY;

-- Allow public access (via anon key)
DROP POLICY IF EXISTS "Allow all on employees" ON public.employees;
CREATE POLICY "Allow all on employees" ON public.employees FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all on attendance_log" ON public.attendance_log;
CREATE POLICY "Allow all on attendance_log" ON public.attendance_log FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all on payroll_adjustments" ON public.payroll_adjustments;
CREATE POLICY "Allow all on payroll_adjustments" ON public.payroll_adjustments FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all on payroll_summary" ON public.payroll_summary;
CREATE POLICY "Allow all on payroll_summary" ON public.payroll_summary FOR ALL USING (true) WITH CHECK (true);


-- 5. SEED EMPLOYEES DATA
INSERT INTO public.employees (ep_code, nickname, status, base_salary, pay_group, stay_outside, start_date, resign_date, note) VALUES ('EP01', 'Chujai', 'Active', 17000.0, 'Date : 10', 'No', NULL, NULL, '') ON CONFLICT (ep_code) DO UPDATE SET base_salary = EXCLUDED.base_salary, status = EXCLUDED.status;
INSERT INTO public.employees (ep_code, nickname, status, base_salary, pay_group, stay_outside, start_date, resign_date, note) VALUES ('EP02', 'Aem', 'Resigned', 13000.0, 'Date : 10', 'Yes', NULL, NULL, 'พ้นสภาพพนักงาน / ลาออก') ON CONFLICT (ep_code) DO UPDATE SET base_salary = EXCLUDED.base_salary, status = EXCLUDED.status;
INSERT INTO public.employees (ep_code, nickname, status, base_salary, pay_group, stay_outside, start_date, resign_date, note) VALUES ('EP03', 'Ayee', 'Resigned', 0.0, 'Date : 10', 'No', NULL, NULL, 'พ้นสภาพพนักงาน / ลาออก') ON CONFLICT (ep_code) DO UPDATE SET base_salary = EXCLUDED.base_salary, status = EXCLUDED.status;
INSERT INTO public.employees (ep_code, nickname, status, base_salary, pay_group, stay_outside, start_date, resign_date, note) VALUES ('EP04', 'Zin', 'Active', 12000.0, 'Date : 10', 'Yes', NULL, NULL, '') ON CONFLICT (ep_code) DO UPDATE SET base_salary = EXCLUDED.base_salary, status = EXCLUDED.status;
INSERT INTO public.employees (ep_code, nickname, status, base_salary, pay_group, stay_outside, start_date, resign_date, note) VALUES ('EP05', 'Min', 'Active', 14000.0, 'Date : 10', 'No', NULL, NULL, '') ON CONFLICT (ep_code) DO UPDATE SET base_salary = EXCLUDED.base_salary, status = EXCLUDED.status;
INSERT INTO public.employees (ep_code, nickname, status, base_salary, pay_group, stay_outside, start_date, resign_date, note) VALUES ('EP06', 'Soe', 'Active', 12000.0, 'Date : 10', 'Yes', NULL, NULL, '') ON CONFLICT (ep_code) DO UPDATE SET base_salary = EXCLUDED.base_salary, status = EXCLUDED.status;
INSERT INTO public.employees (ep_code, nickname, status, base_salary, pay_group, stay_outside, start_date, resign_date, note) VALUES ('EP07', 'Wai', 'Active', 12500.0, 'Date : 10', 'Yes', NULL, NULL, '') ON CONFLICT (ep_code) DO UPDATE SET base_salary = EXCLUDED.base_salary, status = EXCLUDED.status;
INSERT INTO public.employees (ep_code, nickname, status, base_salary, pay_group, stay_outside, start_date, resign_date, note) VALUES ('EP08', 'S.Tar', 'Active', 12000.0, 'Date : 10', 'Yes', NULL, NULL, '') ON CONFLICT (ep_code) DO UPDATE SET base_salary = EXCLUDED.base_salary, status = EXCLUDED.status;
INSERT INTO public.employees (ep_code, nickname, status, base_salary, pay_group, stay_outside, start_date, resign_date, note) VALUES ('EP09', 'Wan', 'Active', 12000.0, 'Date : 10', 'Yes', NULL, NULL, '') ON CONFLICT (ep_code) DO UPDATE SET base_salary = EXCLUDED.base_salary, status = EXCLUDED.status;
INSERT INTO public.employees (ep_code, nickname, status, base_salary, pay_group, stay_outside, start_date, resign_date, note) VALUES ('EP16', 'T', 'Active', 13000.0, 'Date : 20', 'No', NULL, NULL, '') ON CONFLICT (ep_code) DO UPDATE SET base_salary = EXCLUDED.base_salary, status = EXCLUDED.status;
INSERT INTO public.employees (ep_code, nickname, status, base_salary, pay_group, stay_outside, start_date, resign_date, note) VALUES ('EP17', 'Phyo', 'Active', 12000.0, 'Date : 20', 'Yes', NULL, NULL, '') ON CONFLICT (ep_code) DO UPDATE SET base_salary = EXCLUDED.base_salary, status = EXCLUDED.status;
INSERT INTO public.employees (ep_code, nickname, status, base_salary, pay_group, stay_outside, start_date, resign_date, note) VALUES ('EP18', 'May', 'Active', 12000.0, 'Date : 20', 'Yes', NULL, NULL, '') ON CONFLICT (ep_code) DO UPDATE SET base_salary = EXCLUDED.base_salary, status = EXCLUDED.status;
INSERT INTO public.employees (ep_code, nickname, status, base_salary, pay_group, stay_outside, start_date, resign_date, note) VALUES ('EP19', 'C', 'Active', 13000.0, 'Date : 20', 'No', NULL, NULL, '') ON CONFLICT (ep_code) DO UPDATE SET base_salary = EXCLUDED.base_salary, status = EXCLUDED.status;
INSERT INTO public.employees (ep_code, nickname, status, base_salary, pay_group, stay_outside, start_date, resign_date, note) VALUES ('EP20', 'Nge', 'Active', 13000.0, 'Date : 20', 'Yes', NULL, NULL, 'Upsalary(20/11/2025)+1000') ON CONFLICT (ep_code) DO UPDATE SET base_salary = EXCLUDED.base_salary, status = EXCLUDED.status;
INSERT INTO public.employees (ep_code, nickname, status, base_salary, pay_group, stay_outside, start_date, resign_date, note) VALUES ('EP21', 'Wawa', 'Resigned', 0.0, 'Date : 20', 'No', NULL, NULL, 'พ้นสภาพพนักงาน / ลาออก') ON CONFLICT (ep_code) DO UPDATE SET base_salary = EXCLUDED.base_salary, status = EXCLUDED.status;
INSERT INTO public.employees (ep_code, nickname, status, base_salary, pay_group, stay_outside, start_date, resign_date, note) VALUES ('EP22', 'Meaw', 'Active', 12000.0, 'Date : 20', 'No', NULL, NULL, '') ON CONFLICT (ep_code) DO UPDATE SET base_salary = EXCLUDED.base_salary, status = EXCLUDED.status;
INSERT INTO public.employees (ep_code, nickname, status, base_salary, pay_group, stay_outside, start_date, resign_date, note) VALUES ('EP23', 'Aem', 'Active', 13000.0, 'Date : 20', 'Yes', NULL, NULL, '') ON CONFLICT (ep_code) DO UPDATE SET base_salary = EXCLUDED.base_salary, status = EXCLUDED.status;
INSERT INTO public.employees (ep_code, nickname, status, base_salary, pay_group, stay_outside, start_date, resign_date, note) VALUES ('EP24', 'Su', 'Active', 12000.0, 'Date : 20', 'Yes', NULL, NULL, '') ON CONFLICT (ep_code) DO UPDATE SET base_salary = EXCLUDED.base_salary, status = EXCLUDED.status;
INSERT INTO public.employees (ep_code, nickname, status, base_salary, pay_group, stay_outside, start_date, resign_date, note) VALUES ('EP31', 'Kat', 'Active', 14000.0, 'Date : 1', 'No', NULL, NULL, '') ON CONFLICT (ep_code) DO UPDATE SET base_salary = EXCLUDED.base_salary, status = EXCLUDED.status;
INSERT INTO public.employees (ep_code, nickname, status, base_salary, pay_group, stay_outside, start_date, resign_date, note) VALUES ('EP32', 'Meaw', 'Resigned', 0.0, 'Date : 1', 'Yes', NULL, NULL, 'พ้นสภาพพนักงาน / ลาออก') ON CONFLICT (ep_code) DO UPDATE SET base_salary = EXCLUDED.base_salary, status = EXCLUDED.status;
INSERT INTO public.employees (ep_code, nickname, status, base_salary, pay_group, stay_outside, start_date, resign_date, note) VALUES ('EP33', 'Tualek', 'Active', 12500.0, 'Date : 1', 'Yes', NULL, NULL, '') ON CONFLICT (ep_code) DO UPDATE SET base_salary = EXCLUDED.base_salary, status = EXCLUDED.status;
INSERT INTO public.employees (ep_code, nickname, status, base_salary, pay_group, stay_outside, start_date, resign_date, note) VALUES ('EP34', 'Thu', 'Active', 15000.0, 'Date : 1', 'Yes', NULL, NULL, '') ON CONFLICT (ep_code) DO UPDATE SET base_salary = EXCLUDED.base_salary, status = EXCLUDED.status;
INSERT INTO public.employees (ep_code, nickname, status, base_salary, pay_group, stay_outside, start_date, resign_date, note) VALUES ('EP35', 'Sandi', 'Active', 12000.0, 'Date : 1', 'Yes', NULL, NULL, '') ON CONFLICT (ep_code) DO UPDATE SET base_salary = EXCLUDED.base_salary, status = EXCLUDED.status;
INSERT INTO public.employees (ep_code, nickname, status, base_salary, pay_group, stay_outside, start_date, resign_date, note) VALUES ('EP36', 'Moe', 'Active', 12000.0, 'Date : 1', 'Yes', NULL, NULL, '') ON CONFLICT (ep_code) DO UPDATE SET base_salary = EXCLUDED.base_salary, status = EXCLUDED.status;
INSERT INTO public.employees (ep_code, nickname, status, base_salary, pay_group, stay_outside, start_date, resign_date, note) VALUES ('EP37', 'Aye', 'Active', 12000.0, 'Date : 1', 'Yes', NULL, NULL, '') ON CONFLICT (ep_code) DO UPDATE SET base_salary = EXCLUDED.base_salary, status = EXCLUDED.status;
INSERT INTO public.employees (ep_code, nickname, status, base_salary, pay_group, stay_outside, start_date, resign_date, note) VALUES ('EP38', 'T.Tar', 'Active', 12000.0, 'Date : 1', 'Yes', NULL, NULL, '') ON CONFLICT (ep_code) DO UPDATE SET base_salary = EXCLUDED.base_salary, status = EXCLUDED.status;
INSERT INTO public.employees (ep_code, nickname, status, base_salary, pay_group, stay_outside, start_date, resign_date, note) VALUES ('EP39', 'Cherry', 'Active', 12000.0, 'Date : 1', 'Yes', NULL, NULL, '') ON CONFLICT (ep_code) DO UPDATE SET base_salary = EXCLUDED.base_salary, status = EXCLUDED.status;
INSERT INTO public.employees (ep_code, nickname, status, base_salary, pay_group, stay_outside, start_date, resign_date, note) VALUES ('EP40', 'Ei Phyo', 'Active', 12000.0, 'Date : 1', 'Yes', NULL, NULL, '') ON CONFLICT (ep_code) DO UPDATE SET base_salary = EXCLUDED.base_salary, status = EXCLUDED.status;
INSERT INTO public.employees (ep_code, nickname, status, base_salary, pay_group, stay_outside, start_date, resign_date, note) VALUES ('EP46', 'U', 'Active', 14000.0, 'Date : 1', 'No', NULL, NULL, '') ON CONFLICT (ep_code) DO UPDATE SET base_salary = EXCLUDED.base_salary, status = EXCLUDED.status;
INSERT INTO public.employees (ep_code, nickname, status, base_salary, pay_group, stay_outside, start_date, resign_date, note) VALUES ('EP47', 'Tidtee', 'Active', 14000.0, 'Date : 1', 'No', NULL, NULL, '') ON CONFLICT (ep_code) DO UPDATE SET base_salary = EXCLUDED.base_salary, status = EXCLUDED.status;
INSERT INTO public.employees (ep_code, nickname, status, base_salary, pay_group, stay_outside, start_date, resign_date, note) VALUES ('EP48', 'Waii', 'Active', 12000.0, 'Date : 1', 'No', NULL, NULL, '') ON CONFLICT (ep_code) DO UPDATE SET base_salary = EXCLUDED.base_salary, status = EXCLUDED.status;