import os
import openpyxl
import datetime

EXCEL_PATH = r"C:\Users\User\Desktop\Signature_Payroll_V3_Standard.xlsx"
OUTPUT_SQL = r"C:\Users\User\Desktop\Churnkub\signature_payroll_app\supabase_schema.sql"

wb = openpyxl.load_workbook(EXCEL_PATH, data_only=True)

def sql_str(val):
    if val is None:
        return 'NULL'
    s = str(val).strip().replace("'", "''")
    return f"'{s}'"

def sql_date(val):
    if isinstance(val, (datetime.datetime, datetime.date)):
        return f"'{val.strftime('%Y-%m-%d')}'"
    if val:
        s = str(val).strip()[:10]
        return f"'{s}'"
    return 'NULL'

def sql_num(val, default=0.0):
    try:
        return str(float(val)) if val is not None else str(default)
    except Exception:
        return str(default)

def sql_int(val, default=0):
    try:
        return str(int(val)) if val is not None else str(default)
    except Exception:
        return str(default)

sql_lines = []

sql_lines.append('''-- =============================================================
-- SIGNATURE PAYROLL SUITE - SUPABASE DATABASE SCHEMA
-- =============================================================

-- 1. EMPLOYEES TABLE
CREATE TABLE IF NOT EXISTS public.employees (
    ep_code TEXT PRIMARY KEY,
    nickname TEXT NOT NULL,
    status TEXT DEFAULT 'Active',
    base_salary NUMERIC DEFAULT 0,
    pay_group TEXT DEFAULT 'Date : 10',
    stay_outside TEXT DEFAULT 'No',
    start_date DATE,
    resign_date DATE,
    note TEXT
);

-- 2. ATTENDANCE LOG TABLE
CREATE TABLE IF NOT EXISTS public.attendance_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    log_id TEXT,
    date DATE NOT NULL,
    ep_code TEXT NOT NULL REFERENCES public.employees(ep_code) ON DELETE CASCADE,
    nickname TEXT,
    category TEXT NOT NULL DEFAULT 'Day-off',
    shift TEXT DEFAULT 'Normal',
    units NUMERIC DEFAULT 1.0,
    note TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 3. PAYROLL ADJUSTMENTS TABLE
CREATE TABLE IF NOT EXISTS public.payroll_adjustments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    adj_id TEXT,
    period TEXT NOT NULL,
    due_date DATE,
    ep_code TEXT NOT NULL REFERENCES public.employees(ep_code) ON DELETE CASCADE,
    nickname TEXT,
    type TEXT NOT NULL DEFAULT 'Deduction',
    category TEXT NOT NULL DEFAULT 'Advance',
    description TEXT,
    amount NUMERIC NOT NULL DEFAULT 0,
    status TEXT DEFAULT 'Pending',
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 4. PAYROLL SUMMARY TABLE
CREATE TABLE IF NOT EXISTS public.payroll_summary (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payroll_id TEXT,
    period TEXT NOT NULL,
    ep_code TEXT NOT NULL REFERENCES public.employees(ep_code) ON DELETE CASCADE,
    nickname TEXT,
    pay_type TEXT DEFAULT 'Full Month',
    base_salary NUMERIC DEFAULT 0,
    work_days INT DEFAULT 26,
    day_off INT DEFAULT 4,
    sick INT DEFAULT 0,
    half_day INT DEFAULT 0,
    ot_days INT DEFAULT 0,
    base_pay NUMERIC DEFAULT 0,
    total_extra NUMERIC DEFAULT 0,
    total_deduction NUMERIC DEFAULT 0,
    net_pay NUMERIC DEFAULT 0,
    status TEXT DEFAULT 'Approved',
    note TEXT,
    created_at TIMESTAMPTZ DEFAULT now(),
    UNIQUE (period, ep_code)
);

-- Enable RLS
ALTER TABLE public.employees ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.attendance_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payroll_adjustments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payroll_summary ENABLE ROW LEVEL SECURITY;

-- Allow public access (via anon key)
DROP POLICY IF EXISTS "Allow all on employees" ON public.employees;
CREATE POLICY "Allow all on employees" ON public.employees FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all on attendance_log" ON public.attendance_log;
CREATE POLICY "Allow all on attendance_log" ON public.attendance_log FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all on payroll_adjustments" ON public.payroll_adjustments;
CREATE POLICY "Allow all on payroll_adjustments" ON public.payroll_adjustments FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all on payroll_summary" ON public.payroll_summary;
CREATE POLICY "Allow all on payroll_summary" ON public.payroll_summary FOR ALL USING (true) WITH CHECK (true);
''')

# Insert Employees
emp_sheet = wb['Employees']
sql_lines.append('\n-- 5. SEED EMPLOYEES DATA')
for r in list(emp_sheet.iter_rows(min_row=2, values_only=True)):
    if r and r[0]:
        ep = sql_str(r[0])
        nick = sql_str(r[1])
        status = sql_str(r[2] if r[2] else 'Active')
        salary = sql_num(r[3])
        grp = sql_str(r[4] if r[4] else 'Date : 10')
        stay = sql_str(r[5] if r[5] else 'No')
        s_date = sql_date(r[6])
        r_date = sql_date(r[7])
        note = sql_str(r[8] if len(r) > 8 and r[8] else '')
        sql_lines.append(f"INSERT INTO public.employees (ep_code, nickname, status, base_salary, pay_group, stay_outside, start_date, resign_date, note) VALUES ({ep}, {nick}, {status}, {salary}, {grp}, {stay}, {s_date}, {r_date}, {note}) ON CONFLICT (ep_code) DO UPDATE SET base_salary = EXCLUDED.base_salary, status = EXCLUDED.status;")

os.makedirs(os.path.dirname(OUTPUT_SQL), exist_ok=True)
with open(OUTPUT_SQL, 'w', encoding='utf-8') as f:
    f.write('\n'.join(sql_lines))

print(f"Generated {OUTPUT_SQL} successfully!")
